server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paste_code?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl